my_app/urls.py
from django.urls import path

from my_app.views import (
    index,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskChangeStatusView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list"
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create"
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete"
    ),
    path(
        "create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "<int:pk>/change/",
        TaskChangeStatusView.as_view(),
        name="change-status"
    ),
]

app_name = "my_app"

task_manager/urls.py
from django.urls import path

from task_manager.views import (
    index,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskChangeStatusView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list"
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create"
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete"
    ),
    path(
        "create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "<int:pk>/change/",
        TaskChangeStatusView.as_view(),
        name="change-status"
    ),
]

app_name = "task_manager"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("task_manager.urls", namespace="task_manager")),
    path("accounts/", include("django.contrib.auth.urls")),
]

task_manager/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    start_date = models.DateTimeField(auto_now_add=True)
    finish_date = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)
    tags = models.ManyToManyField(
        Tag,
        related_name="tasks"
    )

    class Meta:
        ordering = ["status", "-start_date"]

    def toggle_status(self):
        self.status = not self.status
        self.save()

task_manager/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic, View

from task_manager.models import Tag, Task


def index(request):
    """View function for the home page of the site."""
    task = Task.objects.all()
    tag = Tag.objects.all()
    context = {
        "task": task,
        "tag": tag,
    }
    return render(request, "task_manager/index.html", context=context)


class TagListView(LoginRequiredMixin, generic.ListView):
    model = Tag
    paginate_by = 2


class TagCreateView(LoginRequiredMixin, generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task_manager:tag-list")


class TagUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task_manager:tag-list")


class TagDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("task_manager:tag-list")


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("task_manager:index")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("task_manager:index")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task_manager:index")


class TaskChangeStatusView(LoginRequiredMixin, View):
    # model = Task

    def post(self, request, *args, **kwargs):
        task = Task.objects.get(id=self.kwargs["pk"])
        task.toggle_status()

        return redirect("task_manager:index")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Todo List</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="{% static 'img/favicon.png' %}" rel="icon">
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3">
                {% block sidebar %}
                    {% include "includes/sidebar.html" %}
                {% endblock %}

            </div>
            <div class="col-sm-9">
                {% block content %}

                {% endblock %}
                {% block pagination %}
                  {% include "includes/pagination.html" %}
                {% endblock %}

            </div>
        </div>
    </div>
</body>
</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}

    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page={{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav">
    {% if user.is_authenticated %}
        <li class="list-group-item">User: {{ user.username }} <br>
            <a href="{% url 'logout' %}">Logout</a>
        </li>
    {% else %}
        <li class="list-group-item"><a href="{% url 'login' %}">Login</a></li>
    {% endif %}

        <li class="list-group-item"><a href="{% url 'task_manager:index' %}">Home</a></li>
        <li class="list-group-item"><a href="{% url 'task_manager:tag-list' %}">Tags</a></li>

</ul>

templates/my_app/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Tag?</h1>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="YES, delete" class="btn btn-danger" />
    <a href="{% url 'my_app:tag-list'  %}" class="btn btn-dark">No</a>
  </form>
{% endblock %}

templates/my_app/tag_list.html
{% extends "base.html" %}

{% block content %}
  <div class="header__top">
      <h1>
        Tags
      </h1>
      <div>
          <a href="{% url 'my_app:tag-create' %}" class="btn btn-primary mr-4">Add</a>
      </div>
  </div>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
            {{ tag.name }}
          </td>
          <td>
            <a href="{% url 'my_app:tag-update' pk=tag.id %}" class="btn bg-dark text-light link-to-page">Update</a>
          </td>
          <td>
            <a href="{% url 'my_app:tag-delete' pk=tag.id %}" class="btn bg-dark text-light link-to-page">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>The are no tags</p>
  {% endif %}
{% endblock %}

templates/my_app/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Task?</h1>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="YES, delete" class="btn btn-danger" />
    <a href="{% url 'my_app:index'  %}" class="btn btn-dark">No</a>
  </form>
{% endblock %}

templates/task_manager/index.html
{% extends "base.html" %}

{% block content %}

    <div class="d-flex justify-content-between">
        <h1 class="pb-4">
            TODO List
        </h1>
        <a href="{% url 'task_manager:task-create' %}" class="btn btn-primary m-4">Add task</a>
    </div>

    {% for task in task.all %}
        {% if task.status %}
            <div class="d-flex justify-content-between mr-4">
                <p>
                    <strong>{{ task.content }}</strong>
                    <strong class="text-success">Done</strong>
                </p>
                <form action="{% url 'task_manager:change-status' pk=task.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-secondary pt-1 pb-1">Undo</button>
                </form>
            </div>
            <p>Created: {{ task.start_date }} <i class="text-danger">Deadline: {{ task.finish_date }}</i></p>
        {% else %}
            <div class="d-flex justify-content-between mr-4">
                <p>
                    <strong>{{ task.content }}</strong>
                    <strong class="text-danger">Not done</strong>
                </p>
                <form action="{% url 'task_manager:change-status' pk=task.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success pt-1 pb-1">Complete</button>
                </form>
            </div>
            <p>Created: {{ task.start_date }}</p>

        {% endif %}

        <p class="text-secondary pb-4">
             Tags:
            {% for tag in task.tags.all %}
               {{ tag }}
            {% endfor %}
            <a href="{% url 'task_manager:task-update' pk=task.id %}">Update</a>
            <a href="{% url 'task_manager:task-delete' pk=task.id %}">Delete</a>

        </p>
    {% endfor %}

{% endblock %}

templates/task_manager/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Tag?</h1>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="YES, delete" class="btn btn-danger" />
    <a href="{% url 'task_manager:tag-list'  %}" class="btn btn-dark">No</a>
  </form>
{% endblock %}

templates/task_manager/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/task_manager/tag_list.html
{% extends "base.html" %}

{% block content %}
  <div class="header__top">
      <h1>
        Tags
      </h1>
      <div>
          <a href="{% url 'task_manager:tag-create' %}" class="btn btn-primary mr-4">Add</a>
      </div>
  </div>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
            {{ tag.name }}
          </td>
          <td>
            <a href="{% url 'task_manager:tag-update' pk=tag.id %}" class="btn bg-dark text-light link-to-page">Update</a>
          </td>
          <td>
            <a href="{% url 'task_manager:tag-delete' pk=tag.id %}" class="btn bg-dark text-light link-to-page">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>The are no tags</p>
  {% endif %}
{% endblock %}

templates/task_manager/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Task?</h1>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="YES, delete" class="btn btn-danger" />
    <a href="{% url 'task_manager:index'  %}" class="btn btn-dark">No</a>
  </form>
{% endblock %}

templates/task_manager/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}